DET_SOURCE_DIR: '/gpfs/gsfs1/home/tnguyen/coding/reid_all/AIC21-MTMC/datasets/detection/images/test/S06/'
REID_MODEL: 'reid_model/resnet101_ibn_a_3.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: '/gpfs/gsfs1/home/tnguyen/coding/reid_all/AIC21-MTMC/datasets/detect_merge/'
DATA_DIR: '/gpfs/gsfs1/home/tnguyen/coding/reid_all/AIC21-MTMC/datasets/detect_reid3/'
REID_SIZE_TEST: [384, 384]
